prgrms-web-devcourse/Team-Gaerval-Dadok-FE

package.json, public/icons/close.svg, src/app/mypage/edit/page.tsx, src/app/mypage/page.tsx, src/constants/FormRule/index.ts, src/styles/theme.tsx, src/ui/LinkAvatar/index.tsx, src/ui/UserAvatar/index.tsx, src/ui/UserForm/UserInput/index.tsx, src/ui/UserForm/index.tsx, tsconfig.json, yarn.lock
* 마이페이지를 마크업 했습니다.
* 프로필 페이지와 수정 페이지에서 다른 UI를 제공하는 것이 더 좋을 것 같아서 두 페이지의 디자인 다르게 적용했습니다.
* 어제 회의 내용을 반영하여 폰트 사이즈를 theme 에 설정해두었습니다.
* 피그마에 있는 상단 버튼과 폼 이벤트를 연결하는데 생각보다 복잡해서 우선 폼 안에 버튼을 구현하였습니다.
* 데모데이 이후에 적용하도록 하겠습니다.
- Close #28
=> [#28] 마이페이지 마크업

src/app/book/[id]/page.tsx, src/app/book/page.tsx, src/app/layout.tsx, src/ui/BottomNavigation/index.tsx, src/ui/CreateMeeting/SelectingBook/SearchingBook/index.tsx
* 책 검색 페이지 마크업 
* 책 상세 페이지 마크업 
시간이 촉박하여 하나의 PR로 올린 점 양해 부탁드립니다.
@WooDaeHyun 책 검색 페이지에 SearchBook 컴포넌트를 사용했습니다. 해당 컴포넌트에 사이즈가 고정값으로 작성되어 있어서 제거했습니다. 여러 곳에서 사용하는 컴포넌트라면 사이즈와 관련된 Prop을 받거나, wrapper 요소의 크기를 따라가게끔 하는 것이 좋을 것 같습니다.
- Close #59
=> [#59] 책 검색 페이지 & 책 상세 페이지 마크업

next.config.js, src/apis/core/axios.ts
* 백엔드 서버에 SSL 인증서가 적용되지 않아 클라이언트에서 Proxy 설정을 했습니다.
* next.js 에서 제공하는 rewrites 기능을 이용해 Proxy 설정을 했습니다.
* /api~ 로 가는 모든 요청들은 NEXT_PUBLIC_API_URL/api~ 로 넘어갑니다.
- Close #80
=> [#80] mixedContent 이슈 해결을 위한 URL 프록시 적용

next.config.js, src/ui/Meeting/MeetingSearch/index.tsx, src/ui/Meeting/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 리스트 페이지 검색창 구현
MeetingSearch 컴포넌트에서 input과 select값을 각각 저장해서 submit이벤트 발생 시 객체에 담아서 
MeetingPageContainer컴포넌트로 올려서 검색 API 호출해서 리스트를 렌더링해주도록 로직을 구현했는데 어색하거나 이상한 부분이 있을까요? 가감없이 말씀해 주시면 많은 도움이 될 것 같습니다 ㅎㅎ!! 
- Close #74
=> [#74] 모임 리스트 페이지 검색창 구현

src/app/login/redirect/page.tsx, src/hooks/auth/atoms/index.ts, src/hooks/auth/index.ts, src/hooks/auth/useAuth.ts, src/ui/AuthRequired/index.tsx
- acessToken은 Recoil로 관리됩니다.
- 새로고침 시 localStorage에 저장된 token 값을 가져옵니다.
- Auth 관련 hook(useAuth)을 작성했습니다.
- login 시 useAuth 훅을 사용하도록 수정했습니다.
이름 | 타입 | 역할
-- | -- | --
isAuthed | boolean | accessToken의 유무에 따라 인증된 상태인지 아닌지를 반환합니다.
setAuth | 함수 | 새로운 accessToken을 저장하기 위한 함수입니다. (로그인 시 사용)
removeAuth | 함수 | 관리되고 있는 accessToken을 삭제합니다. (로그아웃 시 사용)
아래와 같이 import해서 사용하시면 됩니다!
```ts
import { useAuth } from '@/hooks/auth';
const { isAuthed, setAuth, removeAuth } = useAuth();
...
```
로그인 후 사용되어야하는 페이지인 경우, `AuthRequired`를 감싸주세요!
login 페이지로 replace됩니다.
```ts
import AuthRequired from '@/ui/AuthRequired';
const Page = () => {
return (
<AuthRequired>
...
</AuthRequired>
);
};
export default Page;
```
- 사용하는데 불편할 것 같은 부분이 있다면 말씀해주세요!!
- Close #79
=> [#79] useAuth 훅, AuthRequired 구현

src/apis/job/index.ts, src/app/profile/me/add/page.tsx, src/app/profile/me/page.tsx, src/constants/FormRule/index.ts, src/queries/job/useAllJobQuery/index.ts, src/types/job.ts, src/types/user.ts, src/ui/AdditionalProfileForm/index.tsx, src/ui/CreateMeeting/CreateMeetingForm/index.tsx, src/ui/FormInput/index.tsx, src/ui/ProfileInfo/index.tsx
* 내 프로필을 조회할 때 닉네임이나 직업 정보가 존재하지 않는 경우 추가 정보 입력 페이지로 리다이렉트 시킵니다.
* 모든 직업정보 조회 API를 연동하여 직군, 직업 목록을 서버에서 받아옵니다.
* 직업관련 타입을 수정했습니다.
* submit 이벤트는 아직 구현되지 않았습니다.
* 직업과 관련된 response를 수정 요청 해둔 상태입니다.
- Close #73
=> [#73] 프로필 추가정보 입력 페이지 API 연동

src/app/profile/me/layout.tsx, src/app/profile/me/page.tsx, src/ui/BottomNavigation/NavigationItem/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/LoginBottomSheet/index.tsx
* 로그인하지 않은 사용자는 프로필 페이지로 접근할 수 없도록 수정해두었습니다.
* 바텀 네비게이션에서 프로필 페이지로 접근하려하면 바텀 시트를 띄워줍니다.
- Close #94
=> [#94] 로그인하지 않은 사용자 프로필 페이지 접근 못하도록 수정

src/apis/core/axios.ts
accessToken이 없는 경우, axios Authorization 헤더가 들어가지 않도록 수정했습니다.
- Close #114
=> [#114] axios header accessToken이 null인 경우 예외처리

src/apis/Meeting/index.ts, src/queries/meeting/useMeetingCommentsQuery/index.tsx, src/queries/meeting/useMeetingDetailCommentsListQuery/index.tsx, src/queries/meeting/useMeetingInfoQuery/index.tsx, src/types/meetingDetailCommentsList.ts, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 댓글 API 연동
- 현재 API 중에 nickname과 같은 정보들이 빠져있어 요청해 놓은 상태이고 그 외 부분들은 연동을 해놓았습니다.
- 현재 들어있는 DUMMY_DATA가 존재하지 않습니다.
- API 요청과 response는 정상적으로 오는것을 확인했습니다. 
- 추후 댓글 생성 API 연동 후 더미 데이터를 많이 만들어 놓겠습니다~
- Close #128
=> [#128] 모임 상세 페이지 댓글 리스트 API 연동

src/apis/Meeting/index.ts, src/queries/meeting/useMeetingDetailCommentsListQuery/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 참여 버튼 클릭시 모임 참여 API 연동 및 모임 상세 조회 API refetch()
- Close #135
=> [#135] 모임 참여 API 연동

src/apis/Meeting/index.ts, src/types/meetingDetailCommentsList.ts, src/ui/MeetingDetail/CommentInputBox/index.tsx, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 댓글 생성 API 연동
- 모임 상세 페이지 댓글정보에 nickname추가
- 현재 로그인한 유저가 참여한 모임에서 해당 유저가 작성한 댓글의 경우 수정/삭제 버튼 노출
- Close #138
=> [#138] 모임 상세 페이지 댓글 생성 API 연동

src/ui/MeetingDetail/MeetingInfo/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 보기 페이지에서 모임장인 user는 모임 수정하기 버튼 노출
- 모임 상세 보기 페이지에서 모임장인 user는 모임 삭제하기 버튼 노출
- 모임 수정하기 버튼 클릭시 -> 모임 리스트 페이지로 router push (모임 수정하기 페이지 완성시 수정 예정)
- 모임 삭제하기 버튼은 API 연결하기 전입니다.
- 현재 모달, toast, bottomSheet이 필요한 기능과 관련하여 어떤 것을 적용할지 정확하게 결정하지 않아 우선 기능을 위주로 구현했습니다.
- 모임 삭제가 불가능한 경우(ex 모임원이 1명 초과인 경우) 알림 메세지 UI 필요
- 모임 삭제하기의 경우에는 다시 한 번 재확인하는 기능이 필요
- 모임이 삭제된 경우 삭제가 완료되었다는 UI필요
- 이 세 가지 경우가 필요할 것 같습니다.(우선 기본 기능 구현과 API 연결부터 완료하겠습니다~)
- Close #142
=> [#142] 모임 상세 페이지 모임장 모임 수정 및 삭제 버튼

src/apis/Meeting/index.ts, src/apis/core/axios.ts, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임의 인원이 모임장 1명인 경우 모임 삭제 API 연결
- 모임 삭제 후 모임 목록 페이지로 이동
- 모임 상세 페이지 댓글이 없는 경우 안내 메세지 추가
- Close #147
=> [#147] 모임 삭제 API 연동, 모임 상세 페이지 댓글이 없는 경우 안내 텍스트 추가

src/apis/Meeting/index.ts, src/apis/core/axios.ts, src/ui/MeetingDetail/CommentDeleteModal/index.tsx, src/ui/MeetingDetail/CommentModifyModal/index.tsx, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 댓글 삭제 API 연동
- 댓글 삭제 후 댓글 리스트 refetch
불필요한 코드가 있는지 매의 눈으로 관찰 부탁드립니다 🤩
- Close #173
=> [#173] 모임 상세 페이지 댓글 삭제 API 연동

src/apis/Meeting/index.ts, src/ui/MeetingDetail/CommentModifyModal/index.tsx, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 댓글 수정 API 연결
- 모임 상세 페이지 댓글 삭제 관련해서 URL주소가 조금 바뀌어서 그 부분까지 수정에 넣었습니다.
- comment를 -> comments로 변경
- 이번에는 console.log를 검색해서 찾아내서 지워보았습니다. 혹시나 모를 불필요한 코드가 있다면 매의 눈으로 관찰 부탁드려용~
- Close #175
=> [#175] 모임 상세 페이지 댓글 수정 API 연결

src/apis/meeting/index.ts, src/constants/initialBookGroupComments.ts, src/ui/Meeting/MeetingList/MeetingListItem.tsx, src/ui/Meeting/index.tsx, src/ui/MeetingDetail/CommentInputBox/index.tsx, src/ui/MeetingDetail/CommentsList/GuideMessage.tsx, src/ui/MeetingDetail/CommentsList/commentsDummy.tsx, src/ui/MeetingDetail/CommentsList/index.tsx, src/ui/MeetingDetail/MeetingInfo/index.tsx, src/ui/MeetingDetail/index.tsx
- 로그인 여부, 모임 가입 여부, 모임 공개 여부에 따른 댓글 노출 개수 제한
- 댓글이 아무것도 없는 경우에는 "첫 글의 주인공이 되어주세요" 텍스트 노출
- 로그인o + 비공개 + 미가입 => 더미 데이터 블러처리 노출 및 안내 텍스트 노출
- 로그인x + 비공개 => 더미 데이터 블러처리 노출 및 로그인 버튼 및 안내 텍스트 노출
- 로그인x + 모임 참여 버튼 클릭시 => 로그인 바텀 시트 노출
- 로그인x + 비공개 모임
- 로그인o + 비공개 모임 + 모임 미가입
- 로그인x + 모임 참여버튼 클릭시 로그인 바텀 시트
- 댓글이 하나도 없는 경우에는 모임 공개, 비공개 여부 관계없이 일괄적으로 아래 이미지처럼 보이도록 했습니다.
- Close #212
=> [#212] 조건에 따른 댓글 노출 제한과 안내 텍스트 작성, 모임 참여버튼 클릭시 조건에 따른 바텀시트 노출

src/apis/group/index.ts, src/pages/group/index.tsx, src/queries/group/useEntireGroupsQuery/index.tsx
모임 목록 페이지 무한스크롤 구현
- 바닥에 닿았을 때 Loading과 관련된 처리를 해주어야 하는데, Skeleton 컴포넌트를 넣을 경우 영역은 차지하게 되는데 Skeleton이 적용되지 않는 것을 확인했습니다. 혹시 Skeleton으로 적용할 수 있는 방법이 있을까요?
- Loading... 문구로 Loading 처리를 하여도 깔끔해 보인다는 생각이 들었는데 이 방법도 괜찮을까요? 다른 분들 의견이 궁금합니다.😁
- Close #290
=> [#290] 모임 목록 페이지 무한스크롤 구현

src/apis/book/index.ts, src/queries/book/useRecentSearchesQuery.ts, src/types/book.ts, src/ui/BookSearch/RecentSearches.tsx, src/ui/BookSearch/index.tsx
- 최근 검색어 기능 구현
- 도서 검색 쿼리와 최근 검색어 쿼리가 둘 다 사용되어 코드의 통일성과 명확성을 위해 구조 분해 할당으로 꺼내온 데이터들을 명시적으로 보일 수 있도록 수정했습니다. ex) const bookSearchInfo = useBookSearchQuery({...})로 수정하여 bookSearchInfo.isSuccess
- 현재 API에 맞게 기능을 구현했으나 아직 삭제 및 전체 삭제 기능은 없고, 이미 최근 검색어로 들어가 있는 단어를 다시 검색하는 경우 해당 단어가 다시 0번 인덱스로 이동되어야 하나 해당 기능까지 백엔드에서 아직 구현하지는 않은것 같습니다. 
- 다독다독 서비스의 경우 책 검색에서 디바운스를 통해 자동으로 단어들을 검색하고 있는데, 해당 기능과 최근 검색어 기능과 어울리지는 않는 것 같습니다. submit을 통해 명확하게 검색을 하는 방식으로 변경할 필요가 있을 것 같습니다. 
- 참고 부탁드립니다. 감사합니다~☺️
- Close #321
=> [#321] 최근 검색어 기능 구현

src/pages/book/[bookId]/index.tsx, src/ui/BookDetail/BookInfo.tsx
* `useBookUserInfoQuery` 의 enabled 옵션을 제거하여 로그인하지 않은 사용자가 책 상세 페이지에서 내용을 보지 못하는 문제를 해결했어요.
* 책 상세 페이지에서 더 높은 해상도의 책 표지를 받아오도록 수정했어요.
- Close #347
=> [#347] 로그인하지 않은 사용자가 책 상세 페이지에서 내용을 보지 못하는 문제 해결

src/hooks/useDisclosure.ts, src/stories/Base/Modal.stories.tsx, src/ui/Base/Modal.tsx
- Modal 컴포넌트 작성
~~Modal 컴포넌트는 온전하게 UI로의 역할만 할 수 있게 Modal을 control하는 상태들은 전부 사용하고자 하는 컴포넌트에서 prop으로 넘겨주도록 했고,~~
~~modal 창이 띄워진 후 삭제 버튼 클릭시의 동작도 필요하기에 그에 따른 동작도 prop으로 넘겨 받도록 구현했는데 괜찮은 방법인지 모르겠습니다. 어떻게 생각하시나요?!~~
- Modal 컴포넌트는 오직 모달창이 띄워지는 역할만 할 수 있도록 수정했습니다.
- modal 창이 띄워졌을 때 내부의 제목, 내용, 버튼과 같은 요소는 Modal 컴포넌트를 사용하는 측에서 children으로 넘겨 줄 수 있도록 했습니다.
- useDisclosure 훅을 통해 modal의 isOpen 상태를 관리하도록 변경하였습니다.
- Modal 컴포넌트에 portal을 적용하기 위해 알아보던 중 `headlessui`의 `Modal`을 사용하면 portal을 사용해 Modal을 렌더링하고 있어 별도로 portal을 사용하지는 않았습니다. body 요소 내부에 `id`가 `headlessui-portal-root`라는 `div` 요소를 생성하여 그 안에 Modal 컴포넌트가 들어가고 있습니다.
~~Modal 컴포넌트는 모임삭제 / 댓글삭제 / 책 코멘트 삭제에서 사용될 것으로 예상됩니다.
그런데 title에 따라 *목적격 조사*가 달라지게 되는데 (ex 모임`을`, 댓글`을`, 코멘트`를` ) 이를 통일 시켜주는 방법이 뭐가 좋을지 고민입니다.그렇다고 title props에 -을/-를 까지 붙여 넘겨주는 것은 어색한 것 같고.. …
=> [#365] Modal 컴포넌트

src/stories/Base/RadioButton.stories.tsx, src/ui/Base/RadioButton.tsx
아티클 공유: `label`의 `htmlFor`속성과 `input`의 `name`속성을 같게 해주어야 서로 접근(?)할 수 있다! [참고 MDN 문서](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#selecting_a_radio_button_by_default)
아직은 구상이 잘 떠오르지 않습니다만
위 사진과 같이 `직접 입력`을 선택했을 때 `Input` 요소가 나올 수 있도록 하는 기능도 차차 고민해봐야할 것 같습니다!
- Close #398
=> [#398] RadioButton 컴포넌트

public/icons/avatar.svg, src/stories/Base/Avatar.stories.tsx, src/ui/Base/Avatar.tsx
모임 상세 페이지 작업할 때 아바타 컴포넌트가 필요해서 먼저 구현했어요!
- Close #418
=> [#418] Avatar 컴포넌트

src/app/group/page.tsx
`APIGroup` 타입 명세가 수정된 부분이 있었는데, 머지하면서 모임 메인페이지에는 적용이 되지 않아 빌드 과정에서 에러가 발생했어요. 이 부분 해결했습니다!
=> [fix] group 페이지 타입 에러 수정

src/app/group/[groupId]/join/page.tsx, src/app/group/[groupId]/page.tsx, src/hooks/group/useJoinBookGroup.ts, src/v1/bookGroup/BookGroupNavigation.tsx, src/v1/bookGroup/detail/JoinBookGroupButton.tsx
- 모임 가입 페이지 구현했어요.
- 모임 가입 문제가 없거나 사용자가 이미 모임의 멤버인 경우, 해당 페이지에 접근하면 not found 페이지가 렌더링돼요!
- 모임 가입을 위한 반복되는 로직은 `useJoinBookGroup` custom hooks으로 추출했어요.
- 모임 상세 페이지에서 사용하는 `BookGroupNavigation.BackButton` 컴포넌트의 props와 내부 로직을 수정했어요.
- Close #455
=> [#455] [모임 상세] 모임 가입 문제 페이지

src/app/profile/me/group/page.tsx, src/v1/base/BackButton.tsx, src/v1/base/TopNavigation.tsx, src/v1/bookGroup/BookGroupStatus.tsx, src/v1/bookGroup/DetailBookGroupCard.tsx, src/v1/bookGroup/SimpleBookGroupCard.tsx
* 내가 가입한 모임의 상세 페이지를 구현했어요.
* DetailBookGroupCard 컴포넌트의 스타일을 디자인에 맞게 수정했어요.
* DetailBookGroupCard 컴포넌트에서 Title 이 줄바꿈 되지 않도록 스타일을 추가헸어요. 괜찮을까요?
- Close #467
=> [#467] 내가 가입한 모임 상세 페이지

public/icons/hamburger.svg, src/stories/base/Menu.stories.tsx, src/v1/base/BottomSheet.tsx, src/v1/base/Menu.tsx
- Menu 컴포넌트를 2가지 형태로 구현했어요.
1. Dropdown
- 화면의 여유공간에 따라 드롭다운 리스트의 위치가 유동적으로 움직이도록 구현하고 싶었지만 구현하는데 오래걸릴 것 같았고, 디자인상 모든 Menu 버튼이 화면의 우측에 위치하고 있어서 드롭다운 리스트를 **버튼의 하단 우측에 고정**시켜뒀어요.
2. BottomSheet
- 앱뷰에 친화적인 BottomSheet 형태로 리스트가 보여져도 좋을 것 같아서 구현해봤어요!
- 저는 Dropdown 리스트가 기능적으로 완벽하지 않아서 BottomSheet 리스트를 사용하면 좋을 것 같은데, 여러분들의 의견을 듣고싶어요! 자유롭게 말씀해주세요!! 🙌🏻
- Close #470
=> [#470] Menu 컴포넌트

src/app/group/[groupId]/page.tsx, src/constants/url.ts, src/v1/book/BookCover.tsx
- 로그인하지 않은 경우, `모임 참여하기` 버튼 대신 `로그인 및 회원가입` BottomActionButton이 노출되도록 수정했어요.
- Close #476
=> [#476] [모임 상세] 비로그인 시 모임 참여하기 버튼 비활성화

src/app/group/page.tsx, src/app/profile/me/group/page.tsx, src/queries/group/useMyGroupQuery.ts, src/types/group.ts, src/v1/bookGroup/DetailBookGroupCard.tsx, src/v1/bookGroup/SimpleBookGroupCard.tsx
- 현재 모임 참여 인원이 보이지 않는 이슈를 해결했어요.
- 변경된 api 응답 스키마를 APIGroup 타입에 적용했어요.
- `myGroupsQuery`에 suspense를 적용했어요.
- 로그인되어 있을 때만 요청이 가도록 수정했어요.
- `SimpleBookGroupCard`, `DetailBookGroupCard`, `MyBookGroupList`의 스켈레톤 컴포넌트를 작성하고 적용했어요.
- Close #453
=> [#453] [모임] 모임 목록 페이지 개선

src/app/layout.tsx, src/v1/base/TopNavigation.tsx, src/v1/layout/Layout.tsx
* TopNavigation 컴포넌트가 항상 상단에 고정될 수 있도록 스타일을 수정했어요.
- Close #443
=> [#443] TopNavigation 컴포넌트 스타일 fixed 적용

src/types/book.ts, src/v1/bookSearch/BestSellers.tsx
베스트셀러를 클릭하면 해당 도서 정보를 DB에 저장하고 다독다독 책 상세 페이지로 이동합니다.
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/f9e1cfe6-acee-42fc-b981-5b57adab2e1e
- Close #491
=> [#491] [도서 검색] 베스트셀러 클릭 시 라우팅 경로 수정 (알라딘 -> 다독다독)

src/hooks/useFunnel.tsx, src/utils/assert.ts, src/v1/base/Funnel/Funnel.tsx
모임생성 퍼널 구현시 활용하게 될 use-funnel을 작성했어요
도메인 이슈로 다른 배포환경에서 테스트한 영상으로 대체했어요
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/af993b3d-94ec-460c-aad4-19764ced95b5
[여기](https://hookstopia.vercel.app/) 에서 직접 테스트해 볼 수 있어요!
Storybook을 작성하지 못해 번거로우시겠지만... 😢
활용 예시 코드는 아래 링크에서 확인할 수 있어요...!
[퍼널](https://github.com/hanyugeon/hookstopia/blob/main/src/pages/Funnel.tsx), [스텝1](https://github.com/hanyugeon/hookstopia/blob/main/src/components/Funnel/FirstForm.tsx), [스텝2](https://github.com/hanyugeon/hookstopia/blob/main/src/components/Funnel/SecondForm.tsx), [스텝3](https://github.com/hanyugeon/hookstopia/blob/main/src/components/Funnel/ThirdForm.tsx)
```tsx
<FormProvider {...method}>
<form>
<Funnel>
<Funnel.Step name="스텝1">
<FirstForm
setNextStep={() => setStep('스텝2')}
/> …
```
=> [#498] useFunnel 작성

package.json, updateDevHost.js
- 로컬 환경의 hosts 파일을 쉽게 수정할 수 있도록 `updateDevHost.js`를 작성했어요.
- 개발 서버를 실행하기 위해서는 로컬의 hosts 파일에 `dadok.app.local` 호스트명을 추가해야해요!
- #506 에서 언급한 문제를 해결하기 위해 hosts 파일을 계속 수정하다보니 불편함을 느껴 스크립트를 작성해봤어요. 😂
- 개발 서버를 실행하기 전에 `update-host` 스크립트를 먼저 실행해주세요!
- hosts 파일에 쓰기 권한이 필요한 경우, `sudo yarn update-host`와 같은 명령어로 실행해주세요!
`🚀 entry [ 127.0.0.1 dadok.app.local ] added in /etc/hosts!` 로그와 함께 hosts 파일이 업데이트 돼요.
`🚀 entry [ 127.0.0.1 dadok.app.local ] already exists in /etc/hosts!` 로그와 함께 업데이트 없이 프로세스가 종료돼요.
- env 파일에서 host를 불러오면 더 쾌적할 것 같지만.. 추후 리팩토링 해볼게요!
- 개선사항이나 문제가 있다면 편하게 말씀해주세요! 🙌🏻
- Close #506
=> [#506] 로컬 환경에서 Host 수정

src/app/profile/me/page.tsx
로그인시 프로필 페이지에 햄버거 메뉴를 추가했어요.
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/bc476574-575f-4ee8-b3ba-59976014d4c6
로컬에서 로그인했을 때 쿠키에 RefreshToken이 담기지 않아
배포환경에서 직접 로그인하여 받은 RefreshToken을 로컬환경으로 복사하여 테스트를 진행했습니다
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/2a88221f-0334-4d20-866d-0bb79f8d8341
이제 더 이상 로그아웃 이후, query 데이터가 fresh 상태로 남지 않습니다.
stale상태로 넘기기 보다 개인정보인 만큼 removeQuery 메서드로 제거하는게 맞다고 판단했어요.
- Close #507 
- Close #499
=> [#507] [프로필] 로그아웃 햄버거 구현

src/app/layout.tsx, src/components/ContextProvider.tsx, src/styles/global.css, src/v1/base/BottomNavigation.tsx, src/v1/layout/Layout.tsx, tailwind.config.js
=> [#509] [레이아웃] BottomNavigation 버그 및 UI 수정

src/hooks/useOutsideClickRef.ts, src/v1/base/Menu.tsx
- useOutsideClickRef 훅을 구현하고 Menu 컴포넌트에 적용했어요.
- Menu 컴포넌트가 다른 컴포넌트 UI에 가려지지 않도록 background, z-index를 설정했어요.
- Close #524
=> [#524] Menu 컴포넌트 개선

src/app/book/search/page.tsx, src/app/bookarchive/page.tsx, src/queries/book/useBookSearchQuery.ts, src/queries/book/useRecentSearchesQuery.ts, src/stories/bookSearch/RecentSearch.stories.tsx, src/stories/bookSearch/SearchResult.stories.tsx, src/styles/global.css, src/v1/book/BookCover.tsx, src/v1/bookSearch/BookSearchList.tsx, src/v1/bookSearch/RecentSearch.tsx, src/v1/bookSearch/RecentSearchList.tsx, src/v1/bookSearch/SearchResult.tsx, src/v1/layout/Layout.tsx
=> [#526] 도서 검색 페이지 개선

src/app/group/[groupId]/not-found.tsx, src/app/group/[groupId]/page.tsx, src/components/ReactQueryProvider.tsx, src/queries/group/useDeleteBookGroupMutation.ts, src/v1/base/Button.tsx, src/v1/base/Toast/ToastProvider.tsx, src/v1/bookGroup/BookGroupNavigation.tsx
- 모임 삭제 기능을 구현했어요.
- 존재하지 않는 모임 페이지에 접근하면 not-found 페이지가 렌더링돼요.
- 존재하지 않는 모임 페이지에서는 runtime 에러가 발생하기 때문에 not-found 페이지를 렌더링하기 위해 ErrorBoundary를 사용했어요.
- Close #505
=> [#505] [모임 상세] 모임 삭제 기능 구현

src/app/group/page.tsx, src/app/profile/me/group/page.tsx, src/v1/base/TopHeader.tsx, src/v1/bookGroup/DetailBookGroupCard.tsx, src/v1/bookGroup/SearchGroup.tsx, src/v1/bookGroup/SimpleBookGroupCard.tsx, tailwind.config.js
- 화면 크기가 줄어들었을 때, 모임상세 카드 요소들이 컨테이너 밖으로 나오는 현상 수정
- 시맨틱 태그 적용
- 불필요한 div 요소 제거
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/7fa78bac-bf49-4bdf-942e-ba8d35f296d0
코멘트로 남겨두었습니다
- Close #535
=> [#535] [독서모임] 독서모임 목록 페이지 개선

package.json, scripts/server.js
- node 환경에서 axios로 https 요청 시 발생하는 'unable to verify first certificate' 에러를 해결했어요.
- next custom 서버 구동 시 `NODE_EXTRA_CA_CERTS` 환경변수에 mkcert rootCA 인증서를 설정하도록 수정했어요.
- Close #549
=> [#549] 'unable to verify first certificate' 에러 해결

.storybook/preview.tsx, src/stories/meta.tsx
- 스토리북 preview에서 Layout를 제거하고, 전체 앱 레이아웃이 필요한 스토리에서는 `appLayoutMeta`를 추가해서 사용할 수 있도록 수정했어요.
```tsx
const meta: Meta<typeof SelectBookStep> = {
title: 'bookGroup/funnel/SelectBookStep',
component: SelectBookStep,
...appLayoutMeta,
};
```
- Close #554
=> [#554] 스토리북 preview decorator에서 Layout 제거

src/stories/bookGroup/create/funnel/EnterTitleStep.stories.tsx, src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx, src/v1/bookGroup/create/steps/EnterTitleStep/fields/TitleField.tsx, src/v1/bookGroup/create/steps/EnterTitleStep/fields/index.ts, src/v1/bookGroup/create/steps/EnterTitleStep/index.ts
모임 이름 퍼널 스텝을 구현했습니다
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/e766abf9-dac6-47d7-ad33-fd63e8160250
- `TitleField.tsx`에는 `useWatch()`를 사용하고있습니다.
- `useWatch()`가 필요한 부분만 `TitleField.tsx`로 분리하여 리랜더링되는 컴포넌트 수를 줄였습니다.
- 간략한 논의 후에 정하였던 폴더구조로 적용해두었습니다.
- Close #562
=> [#562] [모임 생성] 모임 이름 퍼널

src/stories/bookGroup/create/steps/SelectJoinTypeStep.stories.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinPasswordFieldset.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeFieldset.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeRadioCard.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/index.ts, src/v1/bookGroup/create/steps/SelectJoinTypeStep/index.ts, tailwind.config.js
- 모임 생성 퍼널에서 사용될 `모임 가입문제 스텝` 컴포넌트예요.
- 모임 가입문제 유무를 선택하기 위한 라디오 카드 뷰를 관리하고 있어요.
- input radio type의 비제어 컴포넌트예요.
- 모임 가입 문제 유무에 대한 hook form 로직을 관리하는 합성 컴포넌트예요.
- `JoinPasswordFieldset` 컴포넌트와 추상화 레벨을 맞추어 코드 가독성을 높이고 싶어서 합성 컴포넌트 형태로 구현하게 되었어요.
- 하위 컴포넌트 `RadioCardField`에 name prop을 전달하여 form에 register할 수 있어요.
- 모임 가입 문제 있음을 선택한 경우, 가입 문제와 정답 field를 렌더링하는 로직을 담고 있어요.
- 하위 컴포넌트 `AnswerField`, `QuestionField` 각각에 name prop을 전달하여 form에 register할 수 있어요.
- 하위 field들이 모두 FormValueType에 의존하고 있어서 재사용성이 높은 구조는 아니라고 생각돼요.
- 하지만 form context를 사용하고 있는만큼 리렌더링을 최소화하고, 최상단인 Step 컴포넌트에서 구조를 파악하기 쉬운 방향으로 작성하려고 노력하다보니 합성 컴포넌트 형태로 구현하게 되었어요. 고민해보고 더 나은 방향이 떠오른다면 추후 리팩토링해볼게요! 🥲
- Close #563
=> [#563] [모임 생성] 모임 가입문제 퍼널

package.json, patches/next+13.4.7.dev.patch, yarn.lock
- next custom sever 구동 시 webpack hmr이 동작하지 않는 이슈를 해결했어요.
- [patch-package](https://github.com/ds300/patch-package)를 통해 dev 모드에서 `/next/dist/server/lib/render-server-standalone.js` 파일을 수정하는 patch 파일을 만들었어요.
- `postinstall-postinstall` 패키지는 yarn v1에서 함께 설치할 것을 권고하고 있어서 설치하게 되었어요.
- 종속성을 제거하는 상황(`yarn remove`)에서도 postinstall 스크립트가 동작하게 하기 위한 패키지라고 해요.
- yarn(install), yarn add, yarn remove 명령이 실행될 때 postinstall 스크립트를 통해 patch가 적용돼요!
- [next 해당 이슈](https://github.com/vercel/next.js/issues/50461#issuecomment-1596588913)를 참고해서 해결했어요.
- `yarn install` 실행 후 다음과 같이 `patch-package` 명령어가 실행되었는지(`next@13.4.7` 패치가 적용되었다는 로그가 뜨는지) 확인해주세요!
- Close #552
=> [#552] next custom server 구동 시 hmr이 동작하지 않는 문제 해결

src/stories/bookGroup/create/steps/SetUpDetailStep.stories.tsx, src/styles/global.css, src/v1/bookGroup/create/funnel/SetUpDetailStep.tsx, src/v1/bookGroup/create/funnel/index.ts, src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx, src/v1/bookGroup/create/steps/SetUpDetailStep/index.ts
모임 상세 퍼널 개선
- input 컴포넌트의 type이 number일 경우 오른쪽에 나타나는 버튼을 숨겼습니다.
- CustomMemberCountField의 Input 컴포넌트 after 스타일 추가
- watch를 `useWatch()`로 대체
- SelectedBookInfoField에 `book.bookId`를 받을 수 있도록 수정
- Close #561
=> [#561] [모임 생성] 모임 상세 퍼널 개선

src/stories/bookGroup/create/steps/SetUpDetailStep.stories.tsx, src/v1/bookGroup/BookInfoCard.tsx, src/v1/bookGroup/create/funnel/SelectBookStep.tsx, src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
- `BookInfoCard` 컴포넌트에 `onBookRemove` props를 추가했습니다
- `책 선택 스텝`의 input 태그에서 enter 동작시 submit 되던 현상을 제거했습니다
- Close #559
=> [#559] BookInfoCard 컴포넌트 수정 및 goToBookSelectStep 이벤트 추가

src/app/group/page.tsx, src/v1/base/FloatingButton.tsx, tailwind.config.js
FloatingButton이 스크롤 맨 밑에 고정되어있던 버그를 수정했습니다
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/07ff79eb-f896-4496-9225-64e4e92c2300
- Close #574
=> [#574] FloatingButton 버그 수정

src/styles/global.css
Safari 브라우저에서 `DatePicker` UI가 올바르지 않게 표시되는 문제를 해결합니다.
해결후
- Close #578
=> [#578] iOS 환경에서의 DatePicker UI 수정

src/app/profile/me/group/page.tsx, src/app/profile/me/page.tsx, src/v1/profile/bookShelf/ProfileBookshelfPresenter.tsx, src/v1/profile/group/ProfileGroupContainer.tsx, src/v1/profile/group/ProfileGroupPresenter.tsx
- ProfileGroupPresenter 컴포넌트에 모임장 여부를 판단하기 위한 isGroupOwner prop을 추가했어요.
- 내가 참여한 모임 목록 페이지에 SSRSafeSuspense를 적용하여 hydrantion error를 해결했어요.
- 프로필 페이지 참여한 모임의 상하 스크롤을 제거하고, 화면 전체에서 좌우 수크롤이 생기도록 수정했어요.
- Close #585
=> [#585] [프로필 페이지] '참여한 모임' 영역 사용자가 모임장인 모임에 마크 추가

src/apis/book/index.ts, src/app/book/search/page.tsx
도서 검색 이후 도서를 클릭하면
검색할 때 사용됐던 키워드가 최근 검색어로 저장됩니다
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/048ae196-b3ba-445c-b129-4e7bbaacda89
- Close #557
=> [#557] [도서 검색] 최근 검색어 api 요청

src/app/bookshelf/[bookshelfId]/page.tsx, src/queries/bookshelf/useBookShelfInfoQuery.ts, src/styles/global.css, src/v1/bookShelf/BookShelf.tsx, src/v1/bookShelf/BookShelfCard.tsx, src/v1/bookShelf/BookShelfRow.tsx
- 3D 책 컴포넌트가 완전히 로딩되기 전에 placeholder가 보여지도록 수정했어요.
- 책장 페이지를 서버 컴포넌트로 만들었어요.
- 책장 관련 컴포넌트의 스타일을 수정했어요.
- padding을 줄여 3D 책이 보이는 영역을 넓혔어요.
- 내 책장에는 좋아요를 누를 수 없도록 수정했어요.
- Close #591
=> [#591] 3D 책 컴포넌트, 책장 페이지 개선

next.config.js, public/icons/check-stroke.svg, public/icons/check.svg, public/icons/index.ts, src/hocs/withScrollLockOnFocus.tsx, src/hooks/useRemoveVerticalScroll.ts, src/stories/base/ProgressBar.stories.tsx, src/stories/base/Stepper.stories.tsx, src/v1/base/ProgressBar.tsx, src/v1/base/Stepper.tsx, src/v1/bookGroup/create/CreateBookGroupFunnel.tsx, src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinPasswordFieldset.tsx, src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx, tailwind.config.js
- percentage 값을 `value` prop으로 받아 현재 진행정도를 표현하는 ProgressBar 컴포넌트를 구현했어요.
- 스토리북에서 확인할 수 있어요.
- 퍼널 페이지에서 현재 스텝을 표시하기 위한 Stepper 컴포넌트를 구현했어요.
- 스토리북에서 확인할 수 있어요.
- input, textarea 요소에서 타이핑을 위해 focus하는 경우, 상하 scroll이 제거되는 HOC를 구현했어요.
- 퍼널 페이지에 `Stepper`를 적용했어요.
- 각 스텝의 input, textarea 요소에 `withScrollLockOnFocus` HOC를 적용했어요.
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/4f2fe733-e12c-4e9c-a4e1-adc623f80369
- Close #602
=> [#602] [모임 생성] 퍼널 progress bar, stepper 구현

src/app/bookarchive/page.tsx
로그인이된 상태의 북카이브 페이지에서 accessToken을 유효하지 않게 수정할 경우
무한 리랜더링이 되는 현상을 수정합니다.
- Close #612
=> [#612] 북카이브 페이지에서 발생하는 무한 리랜더링 버그 수정

src/app/group/[groupId]/edit/page.tsx, src/app/group/[groupId]/join/page.tsx, src/app/group/create/page.tsx, src/app/profile/me/add/page.tsx, src/app/profile/me/edit/page.tsx, src/app/profile/me/group/page.tsx, src/hocs/withAuthRequired.tsx, src/v1/profile/group/ProfileGroupContainer.tsx
- 페이지 접근 권한을 부여하기 위한 고차 컴포넌트를 작성했어요
- 권한이 없을 시(비로그인 시) `/login` 페이지로 redirect 합니다.
- `Hydration` 에러를 해결하기 위해 내부에 `isAuthenticated`라는 `useState`를 정의했어요
(`isAuthenticated`가 `false`면 래핑된 컴포넌트는 `null`을 `return` 해요.)
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/6d10bece-c33d-407a-98a8-912469b24f21
- Close #608
=> [#608] 페이지 접근 권한 부여

src/stories/base/Button.stories.tsx, src/v1/base/Button.tsx, src/v1/bookGroup/create/steps/EnterTitleStep/EnterTitleStep.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx, src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx
- Button 컴포넌트에 disabled style을 추가했어요.
- 스토리북으로 확인할 수 있어요!
- 모임 생성 퍼널에서 form이 유효하지 않으면 button이 disabled 되도록 수정했어요.
- useForm의 `formState.isValid` 상태를 활용했어요.
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/57716832/36ab25dd-f7ad-4979-b041-d9e065c69286
- Close #556
=> [#556] 버튼 컴포넌트 disabled style 작성

public/icons/check-circle.svg, public/icons/error-circle.svg, public/icons/warning-circle.svg
- Toast svg 아이콘에서 불필요한 clip path 요소를 제거했어요.
- 확인을 위해 toast 타입을 수정해서 캡처했어요!
- Close #625
=> [#625] Toast 컴포넌트 icon이 잘리는 문제 해결

src/app/book/[bookId]/page.tsx, src/app/group/[groupId]/page.tsx, src/styles/global.css, src/v1/base/BottomActionButton.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/SelectJoinTypeStep.tsx, src/v1/bookGroup/create/steps/SetUpDetailStep/SetUpDetailStep.tsx, src/v1/layout/Layout.tsx
PWA환경에서 스마트폰 기본 UI와의 간섭을 제거하기위해
`BottomActionButton`에 `padding-bottom`값을 수정하였습니다.
수정된 `BottomActionButton`의 `padding-bottom`값으로 인해
컨탠츠 하단부가 가려지는 현상을 `.pb-action-button` 커스텀 클래스를 작성하여 해결하였습니다.
- Close #622
=> [#622] BottomActionButton 패딩 수정

next.config.js, src/app/login/page.tsx, src/middleware.ts
- 루트 path '/' 로 접근한 경우, middleware를 통해 쿠키의 refreshToken 유무에 따라 다른 경로로 리다이렉팅되도록 수정했어요.
- refreshToken이 존재하는 경우, `/bookarchive` 로 리다이렉팅
- refreshToken이 없는 경우, `/login` 로 리다이렉팅
- Close #640
=> [#640] 로그인하지 않은 사용자의 진입점을 로그인 페이지로 수정

package.json, src/app/layout.tsx, src/components/common/GoogleAnalytics.tsx, src/utils/gtag.ts, yarn.lock
개르발민족 계정의 구글 애널리틱스 페이지에서 통계를 확인해 볼 수 있어요!
개르발민족 계정 로그인 이후 [여기에서](https://analytics.google.com/analytics/web/?pli=1#/p448011325/reports/intelligenthome?params=_u..nav%3Dmaui) 확인할 수 있어요!
해당 [미디엄 블로그](https://dany-rivera.medium.com/how-to-integrate-google-analytics-on-your-next-js-13-app-easy-guide-c7389666831c)의 내용을 참고하여 구현하였습니다.
1. `utils/gtag.ts`의 `event`와 `pageview` 함수를 통해 페이지가 몇 번 노출되었는지, 이벤트들은 얼마나 동작하였는지 수집해요.
2. `GoogleAnalytics.tsx`컴포넌트에 `gtag.ts` 유틸들을 일괄적으로 import하고 script를 작성해요
3. 최종적으로 `Layout.tsx`에 `GoogleAnalytics.tsx`를 삽입하여 이벤트와 페이지 노출 횟수와 같은 자료를 구글에 전달해요.
- `devDependencies`에 `@types/gtag.js`가 추가되었어요.
- ~~`release` 프로덕션 브랜치에 머지되면 GA가 최종 작동합니다!~~
dadok.app 도메인 모두 통계자료에 집계되고있네요.. 😅
- Close #650
=> [#650] 구글 애널리틱스 추가

src/app/bookshelf/[bookshelfId]/page.tsx, src/app/login/page.tsx, src/app/profile/me/page.tsx, src/components/common/LoginBottomActionButton.tsx, src/components/common/LoginLink.tsx, src/constants/url.ts
- LoignLink 컴포넌트를 구현했어요.
- 페이지 pathname을 search parameter에 담아 동적으로 로그인 url을 생성한 후, Link 태그의 href로 전달해요.
- 추후 다른 OAuth 로그인도 대응하기 위해 `LoginLink` 라고 네이밍했어요.
- Close #659
=> [#659] 로그인 완료 후 이전 페이지로 돌아올 수 있는 기능 구현

src/app/layout.tsx, src/components/common/NavigationSchemaScript.tsx, src/constants/metadata/appleSplashScreens.ts, src/constants/metadata/index.ts, src/constants/metadata/schema.ts
위 이미지는 구글에 "당근"을 검색했을때 나오는 UI예요.
"당근" 검색 결과 처럼 "다독다독"을 검색했을때 저희 서비스가 노출된다면
북카이브, 도서검색, 독서모임, 내프로필 4가지 항목이 보일 수 있도록 네비게이션 스키마를 작성했어요
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/73218463/ebb61aa7-b7d8-4bf7-ad85-2bc42bf837c6
[schema.org](https://validator.schema.org/)에서 네비게이션 스키마 마크업이
올바르게 적용됐는지 테스트하는 영상이에요
`constants/metadata/scheme.ts`에 각 항목에 대한 description을 임시로 제가 적어 두었어요.
- 북카이브: 같은 직군인 유저들의 책장과 인기 도서를 추천받고 인사이트를 넓혀보세요
- 도서검색: 평소에 궁금했거나 함께 이야기 나누고 싶은 도서를 검색해보세요
- 독서모임: 읽고 싶은 책을 선정하고 모임에 참여하여 멤버들과 이야기를 나눠보세요
- 내프로필: 내 책장을 관리하고 참여한 독서 모임들을 확인해보세요
더 자연스럽거나 어울리는 문구가 있다면 적어주셔도 좋아요 🤣 
- Close #657
=> [#657] 네비게이션 스키마 작성

src/app/bookshelf/[bookshelfId]/page.tsx, src/app/profile/me/page.tsx, src/components/bookShelf/BookShelf.tsx, src/components/bookShelf/BookShelfRow.tsx, src/components/profile/bookShelf/ProfileBookshelfPresenter.tsx, src/components/profile/group/ProfileGroupPresenter.tsx, src/components/profile/info/ProfileInfoPresenter.tsx, src/queries/bookshelf/useBookShelfInfoQuery.ts, src/queries/user/useUserProfileQuery.ts, src/utils/converter.ts
- '책장이 비었어요' text 요소를 재사용하기 위해 Bookshelf 합성 컴포넌트에 EmptyText 컴포넌트를 추가했어요.
- 마이 페이지에서 책장, 참여 중인 모임이 비어있는 경우 문구를 노출하도록 수정했어요.
- 내 프로필 페이지 비어있는 경우 문구 노출
- (로그인, 비로그인) 프로필 페이지 상하 패딩 값 작게 수정
- 직군/직업 정보가 없는 경우, 뱃지 제거
- Close #662
=> [#662] [내 프로필] 책장, 참여 중인 모임이 비어있을 때 문구 노출

src/components/bookSearch/RecentSearchList.tsx
로그인한 사용자의
최근 검색어가 존재하지 않을 때
"검색 기록이 없어요!" 문구가 보이도록
수정했어요!
```tsx
const hasKeywords = keywords && keywords?.length !== 0;
...
return (
{hasKeywords ? (
<최근검색어 />
) : (
<p>검색 기록이 없어요!</p>
)
)
```
기존의 버그는 `props`로 받아오는 `keywords`가 빈배열 `[]`일 경우에도
`boolean`값이 `true`이기 때문에 발생한 버그였어요
`hasKeyword`라는 `boolean` 형태의 변수를 만들어 해결했어요
- Close #665
=> [#665] [도서 검색] 최근 검색어 존재하지 않을때 UI 수정

src/app/bookarchive/page.tsx, src/components/bookArchive/BookArchiveForAuth.tsx
- 미들웨어에서 `profile/me/add`로 리다이렉팅 시켜주고있어요
- 이전 처럼 리다이렉팅 되지 않는다면 유저는 텅 빈 북카이브를 보게 되요
- **프로필 정보가 없다면 `BookarchiveForUnAuth` 컴포넌트를 보여주도록 수정했어요**
- **`추천 도서 리스트` 컴포넌트 오른쪽 너비를 오른쪽 화면 끝까지 이어지도록 수정했어요**
이전에도 이야기했던 내용인데 `430px`이상의 크기로 화면을 보았을 때
`BookCover` 컴포넌트가 애매하게 안짤리고 있어서(?) 스크롤인지 모를 수도 있을 것 같아요
`BookCover` 컴포넌트를 수정하는게 좋을지 혹은 이곳에 스크롤인지 알 수 있도록 다른 UI를 추가해야할지 고민이네요 🤔 
~~몇 가지 레퍼런스들을 찾아보고 코멘트에 남겨볼게요..!~~
만약 `BookCover` 컴포넌트는 그대로 두고, 가이드 UI를 추가한다면 해당 레퍼런스를 참고해볼 수 있을 것 같아요!
- Close #667
=> [#667] [북카이브] 유저 로그인 상태의 북카이브 UI 수정

src/middleware.ts
- 추가 프로필을 등록하지 않은 사용자가 모임 생성 페이지에 접근할 수 없도록 middleware에  `/group/create` path를 추가했어요.
- Close #681
=> [#681] [fix] 프로필을 작성하지 않은 사용자가 모임 생성하지 못하도록 수정

src/app/book/sitemap.ts, src/app/bookshelf/sitemap.ts, src/app/group/sitemap.ts, src/app/layout.tsx, src/app/robots.ts, src/app/sitemap.ts, src/constants/metadata/schema.ts, src/constants/url.ts
1. **환경변수에 `NEXT_DEPLOYMENT_URL`를 선언했어요**
``` env
NEXT_PUBLIC_PRODUCTION_URL=https://dev.dadok.app
```
2. `layout.tsx`, `sitemap.ts`, `robots.ts`, `schema.ts`코드에 있는
메타데이터와 관련된 `NEXT_HOST`를 제거하고, `NEXT_DEPLOYMENT_URL`로 대체했어요
``` env
NEXT_PUBLIC_PRODUCTION_URL=https://dev.dadok.app
```
- Close #677
=> [#677] metadata에 프로덕션 URL만 노출되도록 수정

src/app/profile/me/page.tsx, src/components/bookGroup/BookGroupNavigation.tsx, src/components/comment/CommentList.tsx, src/components/common/Menu.tsx
- Dropdown menu를 모바일 뷰에 친화적인 BottomSheet 형태로 수정했어요.
- Close #684
=> [#684] [fix] Dropdown Menu를 BottomSheet로 수정

src/app/book/search/page.tsx, src/app/bookarchive/page.tsx, src/app/group/page.tsx, src/app/layout.tsx, src/app/login/page.tsx, src/app/manifest.webmanifest, src/app/profile/me/page.tsx, src/components/common/TopHeader.tsx, src/components/common/TopNavigation.tsx, src/components/layout/Layout.tsx, src/hooks/useIsScrollAtTop.ts, src/stories/common/TopHeader.stories.tsx
- PWA환경에서 더 이상 StatusBar가 고정 색깔로 표현되지 않아요
- 대신 body 태그가 StatusBar의 영역을 차지합니다.
- top-safe-area 적용으로 컨탠츠가 해당 영역을 침범하지 않도록 했습니다.
- TopHeader를 리팩터링 했어요
- position속성이 fixed로 바뀌었습니다.
- 더 이상 text props에 의존적이지 않습니다. (text props를 제거되고 className props가 추가 되었어요.)
- useIsScrollAtTop 커스텀 훅을 작성했어요
- isScrollAtTop 변수를 통해 스크롤이 아래로 이동하면 TopHeader의 배경이 blur 처리됩니다.
- 리팩터링된 TopHeader 코드
- 새로운 TopHeader가 적용된 `북카이브`, `도서 검색`, `독서 모임`, `내 프로필` 코드
- Close #685
=> [#685] [fix] iOS PWA 환경에서의 status bar 스타일 추가
