prgrms-web-devcourse/Team-Gaerval-Dadok-FE

.github/ISSUE_TEMPLATE/issue-template.md
issue 템플릿의 frontmatter 오타를 수정합니다.
- Close #5
=> [#5] issue 템플릿 frontmatter 오타 수정

package.json
프로젝트 초기 폴더구조를 작성합니다.
다섯번 째 회의록에 작성된 폴더목록과 비교하여
누락된 것이 있는지 확인해주시면 될 것 같습니다!
- Close #8
=> [#8] 초기 폴더구조 작성

.github/workflows/deploy.yaml, .github/workflows/lint.yaml
애플리케이션을 테스트하고 자동으로 배포하기 위한 CI/CD를 구축합니다.
PR이 생성되면 lint 체크를 합니다.
메인 브랜치에 push가 발생하면 vercel 에 자동으로 배포됩니다.
https://dadok.vercel.app
- Close #7
=> [#7] CI/CD 설정

package.json, src/api/axios.ts, yarn.lock
- 팀 노션 페이지에 `.env.local` 내용 추가해두었습니다. 확인해주세요!
- Close #18
=> [#18] axios instance 생성

src/ui/common/BottomSheet/index.tsx
chakra drawer 사용해서 BottomSheet 컴포넌트 구현했습니다.
- 아래는 컴포넌트 동작 확인을 위해 구현한 페이지이기 때문에 참고만 부탁드립니다!
- BottmSheet를 제어하는데 `useDisclosure` 훅을 사용하면 좋을 것 같아요!
- https://chakra-ui.com/docs/hooks/use-disclosure
- props가 간단하긴하지만 `UseDisclosureProps`를 상속하면 직접 선언하지 않아도 되고 더 명시적인 것 같아서 이를 상속하여 type을 정의해봤습니다.
```typescript
interface UseDisclosureProps {
isOpen?: boolean;
defaultIsOpen?: boolean;
onClose?(): void;
onOpen?(): void;
id?: string;
}
```
- 부족한 부분이 있다면 말씀해주세요!
- Close #22
=> [#22] BottomSheet 컴포넌트 구현

src/constants/FormRule/index.ts, src/ui/UserForm/UserInput/index.tsx, src/ui/UserForm/index.tsx
* UserInput 에서 resetField가 작동하지 않는 이슈를 해결했습니다.
* `useFormContext()`를 사용하여 UserInput 의 props 수를 줄였습니다.
* 기존처럼 focus 가 발생했을 때 와 값이 있을 때 close 버튼이 나타납니다. 
- Close #36
=> [#36] UserInput 에서 resetField 작동하지 않는 이슈 해결

.github/ISSUE_TEMPLATE/issue-template.md
Issue Template에 label이 적용되지 않는 오류를 해결했습니다.
- Close #46
=> [#46] Issue, Pull Request 템플릿 수정 > Issue Template label 오류 수정

package.json, src/app/layout.tsx, src/components/ReactQueryProvider.tsx, yarn.lock
- react-query-devtools 설치
- `ReactQueryProvider` 적용
- 부족한 부분 있다면 알려주세요!
- 해당 pr 머지되면 yarn install 한번 해주세요~!!
- Close #57
=> [#57] React Query 초기 세팅

src/app/mybookshelf/page.tsx, src/pages/api/dummyBooks.ts, src/ui/InteractiveBook/InteractiveBookFront.tsx, src/ui/InteractiveBook/InteractiveBookSide.tsx, src/ui/InteractiveBook/InteractiveBookTop.tsx, src/ui/InteractiveBook/index.tsx, src/ui/InteractiveBookShelf/index.tsx, src/ui/MyBookShelfPage/index.tsx
[프리뷰](https://dadok-git-feat-37-gaerval-team.vercel.app/mybookshelf)
- 안쓰이는 코드
- 지저분한 코드
- 보기 불편한 코드
- 중복되는 코드
에 대한 의견과 조언 언제나 대 환영
- 책장 컴포넌트에 책이 space-between으로 인해 왼쪽부터 차근차근 정렬이 되지 않아요 다른 해결방법이 있을까요... ㅜㅜ
- 아직 디자인적으로 많이 부족한데 다음 작업을 위해 우선 머지하는걸로 해야할 것 같습니다 ㅠ
- Close #37
=> [#37] 책장 컴포넌트 마크업

src/app/mybookshelf/page.tsx, src/ui/MyBookShelfPage/index.tsx, src/ui/common/TopNavigation/index.tsx
[프리뷰 링크 바로가기](https://dadok-git-feat-49-gaerval-team.vercel.app/mybookshelf/)
- Close #49
=> [#49] 내 책장 페이지 마크업

src/app/usersbookshelf/page.tsx, src/ui/UsersBookShelfPage/UsersBookShelfHeader.tsx, src/ui/UsersBookShelfPage/UsersBookShelfTag.tsx, src/ui/UsersBookShelfPage/index.tsx, src/ui/common/TopNavigation/index.tsx
- 다른 사람의 책장 페이지
[내 책장 페이지](https://dadok-git-feat-62-gaerval-team.vercel.app/mybookshelf/)
[다른 사용자 책장 페이지](https://dadok-git-feat-62-gaerval-team.vercel.app/usersbookshelf/)
- Close #62
=> [#62] 다른 사람의 책장 페이지 마크업

src/app/login/redirect/page.tsx
client component에 적절한 hook을 사용하도록 수정했습니다. build해서 동작 확인했습니다!
dev 모드에서는 잘 동작해서 production 환경에서도 당연히 잘 될 줄 알았는데..ㅠ.ㅠ 앞으로 잘 확인해서 올릴게요.. 죄송합니다!
- Close #76
=> [#76] login 리다이렉션 이슈 해결

package.json, src/app/layout.tsx, yarn.lock
recoil을 설치하고 RecoilRoot 추가했습니다!
- Close #86
=> [#86] recoil 설치 및 환경 세팅

src/app/profile/me/add/page.tsx, src/app/profile/me/page.tsx, src/ui/AdditionalProfileForm/index.tsx
* 추가정보 입력 페이지로 이동하지 않는 이슈를 수정했습니다.
* 닉네임이 이미 있는 경우 기본값으로 설정합니다.
- Close #99
=> [#99] 추가정보 입력 페이지로 이동하지 않는 이슈

src/apis/bookshelf/index.ts, src/app/bookarchive/page.tsx, src/app/mybookshelf/page.tsx, src/app/usersbookshelf/page.tsx, src/pages/api/dummyBooks.ts, src/queries/bookshelf/useBookshelfBookListQuery/index.ts, src/queries/bookshelf/useBookshelfInfoQuery/index.ts, src/ui/InteractiveBookShelf/index.tsx, src/ui/ProfileInfo/index.tsx
좀 코드가 난잡한 부분이 있는 것 같아요 ㅠㅠㅠ
정리되었으면 하는 부분이나 개선했으면 사항? 말해주세요...
딱히 포인트랄게 떠오르지 않네요....
- Close #85
=> [#85] 책장 페이지에 책 목록 API 연결

src/app/login/redirect/page.tsx
닉네임, 직업, 직군 정보 중 하나라도 없는 경우 /profile/me/add 페이지로 이동합니다.
- Close #90
=> [#90] login 후 추가 정보 입력 페이지로 이동

src/app/profile/me/add/page.tsx, src/app/profile/me/edit/page.tsx, src/ui/AdditionalProfileForm/index.tsx
* 프로필 수정 페이지에 API를 연동했습니다.
- Close #98
=> [#98] 프로필 수정 API 연동

src/apis/Meeting/index.ts, src/queries/meeting/useEntireMeetingListQuery/index.tsx, src/types/meeting.ts, src/ui/Meeting/MeetingList/index.tsx, src/ui/Meeting/index.tsx
- 모임 전체 목록 API 연동
- Close #110
=> [#110]  모임 전체 목록 API 연동

src/ui/BookSearch/index.tsx, src/ui/CreateMeeting/CreateMeetingForm/index.tsx
모임 생성페이지에서도 책 검색 컴포넌트를 사용 가능하도록 수정했습니다.
- Close #108
=> [#108] 모임 생성 페이지에서도 책 검색 컴포넌트 사용 가능하도록 수정

src/ui/common/BottomSheet/index.tsx
* BottomSheet 컴포넌트에서 isOpen prop 조건부 렌더링을 제거했습니다.
- Close #123
=> [#123] bottom sheet가 매끄럽지 않게 닫히지 않는 이슈

src/apis/Meeting/index.ts, src/app/meeting/[id]/page.tsx, src/queries/meeting/useMeetingDetailInfoQuery/index.tsx, src/types/meetingDetail.ts, src/ui/MeetingDetail/MeetingInfo/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 모임정보 API 연결 완료
- Close #120
=> [#120] 모임 상세 페이지 모임정보 API 연결

src/app/book/[id]/page.tsx, src/app/book/page.tsx, src/app/bookarchive/page.tsx, src/app/layout.tsx, src/app/login/page.tsx, src/app/meeting/page.tsx, src/app/profile/me/page.tsx, src/ui/BookSearch/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/CreateMeeting/CreateMeetingForm/index.tsx, src/ui/Meeting/MeetingListHeader/index.tsx, src/ui/Meeting/index.tsx, src/ui/ProfileForm/index.tsx, src/ui/ProfileInfo/index.tsx, src/ui/common/Layout/index.tsx
- Layout 컴포넌트로 분리
- BottomNavigation은 `/bookarchive`, `/book`, `/meeting`, `/profile/me`, `/profile/:id` 에만 우선적으로 적용했습니다!
- Close #118
=> [#118] 전역 패딩 설정

src/app/book/page.tsx, src/app/bookarchive/page.tsx, src/app/meeting/page.tsx, src/app/profile/me/add/page.tsx, src/app/profile/me/edit/page.tsx, src/app/profile/me/page.tsx, src/ui/BookSearch/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/FormInput/index.tsx, src/ui/FormSelect/index.tsx, src/ui/Meeting/MeetingSearch/index.tsx, src/ui/Meeting/index.tsx, src/ui/ProfileInfo/index.tsx, src/ui/common/Layout/index.tsx
* 바텀 네비게이션을 레이아웃 컴포넌트에서 포함하도록 수정했습니다.
* 페이지 전환 시 애니메이션을 적용했습니다.
- Close #75
=> [#75] 페이지 전환 애니메이션 적용

src/app/book/[id]/page.tsx, src/styles/theme.tsx, src/ui/BookDetail/BookComment.tsx, src/ui/BookDetail/BookCommentList.tsx, src/ui/BookDetail/type.ts
- API가 아직 안나와서 타입은 임의로 정의해서 폴더 내부에 뒀습니다! API 나오면 types 폴더 안으로 옮길게요!
- Close #139
=> [#139] 책 상세 페이지 > 코멘트 목록 마크업 수정

src/ui/InteractiveBook/index.tsx, src/ui/InteractiveBookShelf/index.tsx
책장의 책을 클릭하면 책장 상세 페이지로 이동합니다.
코멘트로 남겨두었습니다.
코멘트로 남겨두었습니다. ~~2트~~
- Close #143
=> [#143] 책장 페이지 > 책 클릭시 책장 상세 페이지로 이동

src/hooks/toast/atoms/index.ts, src/hooks/toast/index.ts, src/hooks/toast/useToast.ts, src/ui/AdditionalProfileForm/index.tsx, src/ui/common/Layout/index.tsx, src/ui/common/Toast/ToastItem.tsx, src/ui/common/Toast/index.tsx
* chakra ui 에서 제공하는 Toast 컴포넌트의 커스터마이징이 쉽지 않아 Toast 컴포넌트를 작성했습니다.
* recoil을 사용해서 useToast 훅을 만들었습니다.
- Close #160
=> [#160] 토스트 컴포넌트 작성

src/ui/InteractiveBook/index.tsx
Safari에서 BottomNav와 겹쳐 보이는 버그 수정하였습니다.
- Close #157
=> [#157] Safari에서 BottomNav와 겹쳐 보이는 버그 수정

src/apis/book/index.ts, src/types/book.ts, src/ui/BookDetail/BookCommentList.tsx, src/ui/BookDetail/CreateCommentDrawer.tsx
코멘트 생성 api 연결했습니다!
- Close #169
=> [#169] 책 코멘트 > 코멘트 생성 api 연결

src/apis/core/axios.ts, src/constants/FormRule/index.ts, src/types/meeting.ts, src/ui/FormInput/index.tsx, src/ui/FormRadio/index.tsx, src/ui/MeetingDetail/index.tsx, src/ui/MeetingForm/AddMettingForm.tsx, src/ui/MeetingForm/radioValues.tsx
- 참여 인원 선택 폼 추가
- 모임 미가입자에게 댓글 공개 여부 폼 추가
- 모입 가입시 비밀번호 추가 여부 폼 추가
- 모임 가입 비밀번호 필요시 제출할 문제 폼 추가
- 모임 가입 비밀번호 필요시 제출할 답 폼 추가
- Close #156
=> [#156] 모임 가입 폼 추가

src/apis/book/index.ts, src/queries/book/useBookCommentsQuery.ts, src/types/book.ts, src/ui/BookDetail/BookComment.tsx, src/ui/BookDetail/BookCommentList.tsx
- 현재 코멘트 목록 조회 api에 이슈가 있어서 모든 책의 코멘트가 조회되고 있습니다. 참고 부탁드립니다!
- 자신이 작성한 코멘트는 상단에 위치하고, 수정 및 삭제가 가능합니다.
- Close #170
=> [#170] 책 코멘트 > 코멘트 목록 조회 api 연결

src/constants/FormRule/index.ts, src/ui/MeetingForm/AddMettingForm.tsx
* 모임 생성, 수정시 시작일로 오늘 날짜가 선택되지 않는 이슈를 해결했습니다.
- Close #181
=> [#181] 모임 생성, 수정시 시작일로 오늘 날짜가 선택되지 않는 이슈

src/styles/theme.tsx, src/ui/BookDetail/BookComment.tsx, src/ui/BookDetail/BookCommentList.tsx, src/ui/common/Button/index.tsx
책 상세 페이지에서 코멘트 삭제 모달 마크업했습니다.
- Close #107
=> [#107] 책 상세 페이지 > 코멘트 삭제 모달 마크업

src/apis/recommend/index.ts, src/app/bookarchive/page.tsx, src/queries/recommend/useAuthRecommendedBooks/index.tsx, src/queries/recommend/useAuthRecommendedBookshelf/index.tsx, src/queries/user/useMyProfileQuery/index.ts, src/types/bookshelf.ts, src/ui/BookArchive/BookArchiveForAuth.tsx
로그인한 사용자 책장 추천 api를 연결합니다.
비로그인시에 메인페이지에서 403에러가 발생하던것을 해결하였습니다.
- Close #182
=> [#182] 메인 페이지 > 로그인한 사용자 책장 추천 api 연결

package.json, src/app/_error.tsx, src/app/layout.tsx, yarn.lock
* Layout을 감싸는 에러바운더리를 적용해두었습니다.
* 최대한 각각의 컴포넌트에서 처리하고, **Layout을 감싸는 에러 바운더리에서는 우리가 예상하지 못한 에러를 사용자에게 노출시키지 않는 용도로만 사용**하는게 좋을 것 같아요 !!
- Close #184
=> [#184] 에러 바운더리 설정

src/app/bookarchive/page.tsx, src/app/profile/me/page.tsx, src/queries/bookshelf/useMySummaryBookshelfQuery/index.ts, src/queries/meeting/useMyMeetingListQuery/index.ts, src/queries/user/useMyProfileQuery/index.ts, src/ui/ProfileBookshelf/index.tsx, src/ui/ProfileInfo/index.tsx
* 내 프로펠 페이지에 스켈레톤을 적용했습니다.
* 코멘트 남겨두었습니다.
- Close #193
=> [#193] 내 프로필 페이지 스켈레톤 적용

src/apis/book/index.ts, src/ui/BookDetail/BookComment.tsx, src/ui/BookDetail/BookCommentList.tsx
책 코멘트 삭제 기능 구현했습니다.
- Close #199
=> [#199] 책 상세 페이지 > 코멘트 삭제 기능 구현

src/app/bookarchive/page.tsx, src/app/bookshelf/[bookshelfId]/page.tsx, src/ui/BookArchive/index.tsx
책장 이름에 유저 이름 or 닉네임 중 한가지로 통일
- Close #206
=> [#206] 책장 이름에 유저 이름 or 닉네임 중 한가지로 통일

src/apis/book/index.ts, src/queries/book/useBookUserInfoQuery.ts, src/types/book.ts, src/ui/BookDetail/BookInfo.tsx
책장에 책꽂기 기능 구현했습니다.
- Close #151
=> [#151] 책 상세 페이지 > 책장에 책 꽂기 api 연결

src/app/book/[id]/page.tsx, src/app/meeting/[id]/edit/page.tsx, src/app/meeting/[id]/page.tsx, src/app/meeting/create/page.tsx, src/app/profile/me/edit/page.tsx, src/ui/common/TopNavigation/index.tsx
=> [#179] Top Navigation UI 통일, 뒤로가기 기능 구현

src/apis/recommend/index.ts, src/queries/book/useBookUserInfoQuery.ts, src/ui/BookDetail/BookInfo.tsx
책 상세 페이지에서 책장에 책을 꽂은 사용자를 보여주는 기능을 구현했습니다.
- Close #205
=> [#205] 책 상세 페이지 > 책장에 책 꽂은 사용자 보여주는 api 연결

next.config.js, src/apis/book/index.ts, src/apis/bookshelf/index.ts, src/apis/core/axios.ts, src/apis/job/index.ts, src/apis/meeting/index.ts, src/apis/recommend/index.ts, src/apis/users/index.tsx
서버에 https 가 적용되어 rewrites 설정이 필요하지 않게 되었습니다. rewrites 설정을 지우고, /service-api/ 로 시작하던 api url path 를 /api/로 수정하였습니다.
- Close #220
=> [#220] Next.js rewrites config 제거

src/pages/profile/[userId]/index.tsx, src/ui/common/TopNavigation/index.tsx
* 다른 사용자 프로필 페이지에 스켈레톤 코드를 작성했습니다.
* TopNavigation 컴포넌트의 마진을 제거했습니다.
- Close #222
=> [#222] 다른 사용자 프로필 페이지 스켈레톤 작성

src/ui/common/Toast/ToastItem.tsx, src/ui/common/Toast/index.tsx
* 토스트를 가운데로 정렬했습니다.
* zIndex 값을 10000으로 수정했습니다.
- Close #228
=> [#228] 토스트 가운데 정렬

src/constants/FormRule/index.ts
* 닉네임 정규식을 수정했습니다.
* 서버와 닉네임 정규식을 동일하게 맞춰두었습니다.
- Close #229
=> [#229] 닉네임 정규식 수정

src/pages/meeting/[meetingId]/index.tsx, src/ui/Meeting/MeetingList/MeetingListItem.tsx, src/ui/MeetingDetail/MeetingInfo/index.tsx, src/ui/MeetingDetail/index.tsx
- 모임 상세 페이지 댓글 삭제 모달 변경
- 모임장 모임 수정 삭제 버튼 위치 변경
- 모임 삭제 등 토스트 구현
- Close #227
=> [#227] 모임 상세 페이지 댓글 삭제 모달 UI변경, 모임장 모임 수정 삭제 버튼 위치 변경

src/ui/Meeting/index.tsx, src/ui/MeetingDetail/CommentDeleteModal/index.tsx, src/ui/MeetingDetail/CommentModifyModal/index.tsx, src/ui/MeetingDetail/index.tsx
모임 상세 페이지 댓글 삭제 UI 변경
- Close #239
=> [#239] 모임 상세 페이지 댓글 삭제 UI 변경

src/pages/404.tsx, src/pages/_app.tsx, src/pages/book/[bookId]/index.tsx, src/pages/error.tsx, src/pages/login/index.tsx, src/pages/profile/me/add/index.tsx, src/styles/theme.tsx, src/ui/LoginBottomSheet/index.tsx
글로벌 폰트 적용안되던 Chakra Heading 컴포넌트 제거 하였습니다
- Close #241
=> [#241] 글로벌 폰트 적용안되던 Chakra Heading 컴포넌트 제거

src/ui/BookSearch/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/LoginBottomSheet/index.tsx, src/ui/Meeting/MeetingListHeader/index.tsx, src/ui/MeetingForm/AddMeetingForm.tsx, src/ui/Profile/MyProfile.tsx
=> [#244] 서비스의 디자인 요소들 통일

src/ui/BookSearch/index.tsx, src/ui/InteractiveBookShelf/index.tsx, src/ui/Meeting/MeetingListHeader/index.tsx, src/ui/Meeting/index.tsx
=> [hofix] page header 수정

src/ui/BottomNavigation/NavigationItem/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/common/Layout/index.tsx
=> [#248] 레이아웃 스크롤 중첩

src/ui/BottomNavigation/NavigationItem/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/common/Layout/index.tsx
Reverts prgrms-web-devcourse/Team-Gaerval-Dadok-FE#249
=> Revert "[#248] 레이아웃 스크롤 중첩"

src/ui/BottomNavigation/NavigationItem/index.tsx, src/ui/BottomNavigation/index.tsx, src/ui/common/Layout/index.tsx
=> [#248] 스크롤 중첩 이슈

src/ui/common/Layout/index.tsx
=> [hotfix] 바텀 네비게이션 경로 수정

src/pages/profile/[userId]/index.tsx, src/ui/BookSearch/index.tsx, src/ui/common/Layout/index.tsx
=> [hotfix] 사용자 프로필 페이지 스타일 수정

next.config.js, src/apis/bookshelf/index.ts, src/pages/bookarchive/index.tsx, src/pages/bookshelf/[bookshelfId]/index.tsx, src/queries/bookshelf/useBookshelfBookListQuery/index.ts, src/types/book.ts, src/ui/BookArchive/BookArchiveForAuth.tsx, src/ui/BookArchive/BookArchiveForUnAuth.tsx, src/ui/InteractiveBook/InitialBookData.tsx, src/ui/InteractiveBookShelf/InitialBookShelfData.tsx, src/ui/InteractiveBookShelf/index.tsx
=> [Hotfix] 책검색api cursorId 파라미터 수정

src/ui/common/TopNavigation/index.tsx
상단 네비게이션 커서 포인터 옵션 추가
- Close #270
=> [#270] 상단 네비게이션 > cursor pointer 옵션 삽입

src/ui/Group/GroupComment/CommentDeleteModal.tsx, src/ui/Group/GroupComment/CommentModifyModal.tsx, src/ui/Group/GroupComment/index.tsx
- 모임 상세 페이지 댓글 수정 삭제 햄버거 UI 적용하여 다독 서비스 댓글 수정 삭제 UI 통일
- Close #276
=> [#276] 모임 상세 페이지 댓글 수정 삭제 UI 통일

src/apis/bookshelf/index.ts, src/apis/recommend/index.ts, src/pages/bookshelf/[bookshelfId]/index.tsx, src/queries/bookshelf/useBookshelfBookListQuery/index.ts, src/queries/recommend/useAuthRecommendedBooks/index.tsx, src/queries/recommend/useAuthRecommendedBookshelf/index.tsx, src/types/bookshelf.ts, src/ui/InteractiveBookShelf/index.tsx, src/ui/Profile/ProfileBookshelf.tsx, src/ui/Recommended/RecommendedBookshelf.tsx
보기에 한눈에 알아보기 어렵거나
어색한 타입명들을 수정하는 작업.
타입 이름을 이전보다 안어색(?)하게 개선하였고
반복되는 타입들을 최대한 묶어 보았습니다
개선 가능해 보이는 부분이 있다면 말해주세요!!
- Close #272
=> [#272] Bookshelf Type 정리

src/hooks/auth/atoms/index.ts, src/utils/isClient.ts, src/utils/storage.tsx
client side인 경우에만 storage에 접근할 수 있도록 수정했습니다.
더 좋은 방법이 있다면 말씀해주세요!! 🙏🏻
- Close #296
=> [#296] client side인 경우에만 web storage에 접근할 수 있도록 수정

package.json
package.json dev, start script에 hostname을 설정했습니다.
- Close #301
=> [#301] package.json script에 hostname 설정

src/apis/book/index.ts, src/queries/book/useBookSearchQuery.ts, src/types/book.ts, src/ui/BookSearch/SearchedBook.tsx, src/ui/BookSearch/index.tsx
책 검색 페이지에 무한 스크롤을 적용했습니다.
코멘트 남겨두었습니다.
- Close #291
=> [#291] 책 검색 페이지 무한 스크롤 적용

src/pages/book/[bookId]/index.tsx, src/ui/BookDetail/BookInfo.tsx
책 상세 내용 더보기 링크 구현했습니다.
- 클릭하면 책 상세 내용이 포함된 페이지가 새로운 창에 열립니다.
- Close #303
=> [#303] 책 상세 페이지 > 책 상세 내용 더보기 버튼 구현

src/constants/groupRadioValues.ts, src/styles/theme.tsx, src/ui/BookSearch/SearchedBook.tsx, src/ui/FormRadio/index.tsx, src/ui/Group/AddGroupForm.tsx, src/ui/common/BottomSheet/index.tsx, src/ui/common/Button/index.tsx
- 모임 생성 인원 사용자 직접입력 폼 기능 구현
- 생성하기 버튼 UI 변경(필수 입력이 필요한 input 필드가 채워진 경우에 main color로 bgColor가 변경됨)
- 모임 생성 페이지 책 검색 후 책 선택 시, handleClick 함수 호출이 안되는 문제 해결
- 모임 생성 페이지 책 검색 후 책 선택 시 click 이벤트 발생시, handleClick 함수가 호출되지 않는 문제가 발생하여 해당 내용 수정했습니다. 수정 전의 코드가 클로저 패턴으로 구현되어 있는 것 같아 클로저 패턴에 맞게 수정해 두었습니다. 
- Close #293
=> [#293] 모임 생성 인원 사용자 직접입력 기능 구현

src/hooks/useDebounce.ts, src/ui/BookSearch/RecentSearches.tsx, src/ui/BookSearch/index.tsx
- 최근 검색어 기능 마크업
- 최근 검색어 삭제는 API를 추후에 추가할 예정이라고 합니다.
- 모든 검색어 삭제는 API를 추후에 추가할 예정이라고 합니다.
- 최근 검색 기록이 없는 사용자의 경우 보여줄 Text는 API를 연결하면서 추가하겠습니다. (현재는 더미데이터로 넣어놨습니다.)
- 마크업 작업을 했는데 디자인은 제가 보기에 깔끔해 보이게 구현을 했습니다.
- 혹시 디자인 적으로 변경되면 좋겠다 하는 부분이 있으면 말씀해주시면 적극 반영하겠습니다~
- Close #312
=> [#312] 최근 검색어 기능 마크업

src/pages/profile/me/index.tsx, src/ui/BookDetail/BookComment.tsx, src/ui/Group/GroupComment/index.tsx, src/ui/Group/GroupDetail/GroupInfo.tsx, src/ui/common/Menu/Menu.tsx, src/ui/common/Menu/MenuItem.tsx, src/ui/common/Menu/index.ts
로그아웃 / 수정 삭제를 위해 사용되던 Menu 관련 UI에서 공통으로 사용되는 부분을 분리하는 작업 진행했습니다!
`MenuItem` 컴포넌트는 기존 차크라에서 제공하는 MenuItemProps에 `text`가 추가된 인터페이스를 전달받습니다.
- `text` : MenuList에서 보여질 MenuItem 이름
- Close #278
=> [#278] Menu 컴포넌트 분리

src/ui/common/LikeButton/index.tsx
IconButton에 button 엘리먼트를 div로 수정하였습니다
변경사항 한줄밖에 없썽
빨리 리뷰해줭
- Close #328
=> 좋아요 마크업에 버튼이 중복되는 부분 수정

src/pages/error.tsx, src/ui/common/Layout/index.tsx
* 레이아웃 컴포넌트의 높이를 100vh에서 100dvh로 수정했습니다.
* 이전 페이지 영상
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/9b6880c7-1a26-45ca-bc61-85be0d34893e
* 작업한 후 페이지 영상
https://github.com/prgrms-web-devcourse/Team-Gaerval-Dadok-FE/assets/48359052/c992b0d9-067d-4a2d-8e31-d809f11d69cd
- Close #337
=> [#337] 모바일 브라우저에서 콘텐츠 영역이 짧아도 스크롤이 생기는 문제 해결

src/components/ReactQueryProvider.tsx, src/pages/_app.tsx
* 모든 페이지에 접근할 때 마다 캐싱된 데이터를 사용하지 않고 새로 페칭하는 문제가 있었습니다.
* QueryProvider를 분리했습니다.
* 페이지를 이동할 때 마다 QueryClient가 생성되지 않도록 수정했습니다.
- Close #342
=> [#342] 페이지를 이동할 때 마다 QueryClient가 생성되지 않도록 수정

package.json, src/styles/font/index.tsx, yarn.lock
* @next/font를 next/font로 교체했어요.
- Close #
=> [#351] @next/font 를 next/font로 교체

src/ui/common/BottomSheet.tsx
* PropsWithChildren의 제네릭을 통해 타입을 확장하도록 수정했어요
- Close #355
=> [#355] DrawerProps 리팩터링

src/app/layout.tsx, src/components/ContextProvider.tsx, src/styles/font/index.ts, src/styles/global.css, src/styles/theme.tsx, tailwind.config.js
- font
- next/font/local을 활용하여 로컬폰트를 설정하였습니다.
- globalStyle
- chakra-ui와 혼용되는 관계로 global.css에 Todo를 작성하였습니다.
- chakra-ui를 제거하면 global.css에 todo목록을 적용합니다.
- theme
- tailwind.config에 fontSize, fontWeight, colors, fontFamily를 작성하였습니다.
- Close #372
=> [#372] Theme, GlobalStyle, Font 세팅

src/app/layout.tsx, src/stories/Button.tsx, src/stories/Switch.tsx, src/styles/global.css, src/styles/theme.tsx, tailwind.config.js
다독다독 theme에 맞게 Storybook 기본예시 스타일링을 수정합니다.
StoryBook에 theme과 font를 적용합니다.
GlobalTheme과 폰트를 수정합니다.
- Close #376
=> [#376] Storybook 설정 및 GlobalTheme, Font 수정

src/stories/Base/BottomActionButton.stories.tsx, src/ui/Base/BottomActionButton.tsx
BottomActionButton 컴포넌트를 구현했어요.
@gxxrxn 만들어져있는 `Button` 컴포넌트는 요소의 크기를 스타일링 할 수 없어서 새로 만들었어요. 어떻게 하는게 좋을까요?
- Close #363
=> [#363] BottomActionButton 컴포넌트

.github/ISSUE_TEMPLATE/issue-template.md
github issue template에 v.1.0 라벨을 추가했습니다.
- Close #413
=> [#413] Issue 템플릿에 v1.0 라벨 추가

src/v1/bookGroup/DetailBookGroupCard.tsx
- Avartar 컴포넌트로 변경 교체
- 공통 함수로 전환된 내용 수정 (bookGroupStatus로 변경 - 독서모임 Badge 관련)
- Placeholder -> placeholder
- Close #437
=> [#437] [독서모임] Avartar, bookGroupStatus 적용 및 typo 수정

src/v1/base/BottomNavigation.tsx, src/v1/bookShelf/BookShelf.tsx, src/v1/profile/LoginBottomSheet.tsx
- 로그인 바텀시트 작성
- Link 컴포넌트 제거
기존 버튼에는 Next/Link 컴포넌트에 엔드포인트가 노출되고있어요
Next/Link 컴포넌트는 앱 내부 탐색에 최적화 되어있고
외부 주소이동에는 잘 쓰이지 않는것으로 확인되어
onClick 이벤트로 대체했습니다~
- Close #459
=> [#459] [유저 로그인] 로그인 BottomSheet 컴포넌트 작성

src/v1/base/Loading.tsx, tailwind.config.js
- loading animation이 처음 시작될 때 튀어오르지 않는 문제를 해결했어요.
- 간단한 애니메이션 수정이라 리뷰 기간에 올려요..🙏🏻
- 또 생각없이.. 피쳐 브랜치로 만들어서 작업해버렸네요.. 죄송합니다..🫠
- 수정 전
- 수정 후
- Close #463
=> [#463] Loading 컴포넌트 animation 버그 해결

src/stories/base/Drawer.stories.tsx, src/v1/base/Button.tsx, src/v1/base/Drawer.tsx
- Drawer 컴포넌트를 구현했어요.
- 스토리북에서 확인할 수 있어요!
- 프로젝트에 적용하면 아래 gif처럼 동작해요.
- 혹시 어색한 애니메이션이나 스타일이 잘못 적용된 부분이 있다면 말씀해주세요!
- Close #472
=> [#472] Drawer 컴포넌트

src/app/bookarchive/page.tsx, src/queries/bookshelf/useMySummaryBookShelfQuery.ts, src/queries/bookshelf/useUserSummaryBookShelfQuery.ts, src/v1/profile/bookShelf/MyProfileBookshelfContainer.tsx, src/v1/profile/bookShelf/UserProfileBookshelfContainer.tsx
* 군데군데 숨어있던 오타를 수정했어요.
- Close #484
=> [#484] 오타 수정

src/app/book/[bookId]/page.tsx, src/queries/book/useBookInfoQuery.ts, src/v1/book/detail/BookInfo.tsx
- 책 상세 페이지 마크업을 작성했어요.
- BookInfo 스켈레톤 컴포넌트를 작성했어요.
- 마크업만 구현했어요. pr이 복잡해질 것 같아서 북마크, 코멘트 수정 및 삭제 등 api 연결은 다른 이슈에서 작업하겠습니닷..
- Close #495
=> [#495] [책 상세] 책 상세 페이지 마크업

src/app/[...not_found]/page.ts, src/app/error.tsx, src/app/not-found.tsx
* error, not-found 페이지에서 사용되는 차크라 UI 를 제거했어요.
* 개발 환경에서 not found 페이지에 접근하면 계속해서 리프레시 되는 문제를 해결하기 위해 아래 코멘트를 참고했어요. 혹시 정확한 원인과 해결 방법을 아시는 분이 있을까요?
* https://github.com/vercel/next.js/discussions/40000#discussioncomment-6291368
- Close #493
=> [#493] 에러 페이지

src/apis/book/index.ts, src/app/book/[bookId]/page.tsx, src/app/group/[groupId]/page.tsx, src/components/ReactQueryProvider.tsx, src/queries/book/useBookCommentsQuery.ts, src/queries/book/useBookmarkUserQuery.ts, src/queries/book/useCreateBookCommentMutation.ts, src/queries/book/useDeleteBookCommentMutation.ts, src/queries/book/usePatchBookCommentMutation.ts, src/queries/book/useUpdateBookmarkMutation.ts, src/types/book.ts, src/ui/BookDetail/BookCommentList.tsx, src/v1/base/LoginBottomActionButton.tsx, src/v1/book/detail/BookInfo.tsx, src/v1/comment/BookCommentList.tsx, src/v1/comment/CommentDrawer.tsx, src/v1/comment/CommentList.tsx
- 책 북마크, 코멘트 생성/수정/삭제 기능을 구현했어요.
- 이름이나 구조도 조금씩 수정하다보니 file changed가 이렇게나 많아졌어요..😭 죄송합니닷...
- 코드리뷰 좀더 수월하게 하실 수 있도록 코멘트 내일까지 작성해둘게요. 🙇🏻‍♀️
- Close #497
=> [#497] [책 상세] 책 상세 페이지 api 연결

src/queries/group/useDeleteBookGroupCommentMutation.ts, src/queries/group/usePatchBookGroupCommentMutation.ts, src/v1/comment/BookGroupCommentList.tsx
- 모임 게시글을 수정, 삭제하는 기능을 구현했어요.
- Close #512
=> [#512] [모임 상세] 모임 게시글 수정/삭제 기능 구현

src/queries/group/useCreateBookGroupCommentMutation.ts, src/v1/bookGroup/BookGroupNavigation.tsx
- 모임 게시글 작성 기능을 구현했어요
- Close #504
=> [#504] [모임 상세] 모임 게시글 작성 기능 구현

src/stories/base/Input.stories.tsx, src/v1/base/Input.tsx
- Input 컴포넌트에 line style을 추가했어요.
- Close #518
=> [#518] Input 컴포넌트 style 추가

src/apis/core/axios.ts, src/app/login/redirect/page.tsx
- 로그인 redirect 페이지에서 차크라를 제거했어요.
- 유효하지않은 accessToken으로 redirect 페이지에 접근하는 경우, 에러를 catch하여 not-found 페이지로 이동시키는 로직을 추가했어요.
- api 요청이 병렬적으로 이뤄질 때, 토큰 업데이트 요청은 한번만 수행되도록 axios interceptor를 수정했어요.
- Close #529
=> [#529] redirect 페이지 개선, 토큰 업데이트 로직 개선

.vscode/react.code-snippets
vscode snippet을 이용하여 `.tsx`, `.jsx` 파일에서 사용할 수 있는 템플릿을 만들었어요.
- jsx, tsx 파일 안에서 `!jsx` 혹은 `!tsx`를 입력하면 작성된 템플릿을 사용할 수 있어요.
- 파일명을 기반으로 컴포넌트 이름이 생성돼요.
- 빠른 코드 수정을 위해 tab키로 위치를 이동시킬 수 있도록 블록을 잡아뒀어요!
- `컴포넌트명` > `type` > `jsx element` > `컴포넌트 내부` 순서로 이동해요.
- Close #544
=> [#544] vscode react component snippet 작성

src/v1/layout/Layout.tsx
모바일 환경에서의 스크롤 버그 수정했습니다
- Close #548
=> [#548] [레이아웃] 모바일 환경에서의 스크롤 버그 수정 

src/v1/base/BottomActionButton.tsx
BottomActionButton을 수정했어요
`position: absolute` -> `position: fixed right-0 left-0 mx-auto max-w-[43rem]`
`<div />` -> `<footer />`
- Close #564
=> [#564] BottomActionButton 컴포넌트 position 속성 수정

src/hooks/useBodyScrollLock.ts, src/v1/base/Drawer.tsx, src/v1/base/Portal.tsx, src/v1/comment/CommentDrawer.tsx
- Drawer가 body style에 영향을 받지 않도록 positon: fixed로 수정했어요.
- Drawer가 열릴 때 body가 scroll되지 않도록 useBodyScrollLock 훅을 작성했어요.
- Close #571
=> [#571] Drawer 컴포넌트 style 개선

src/v1/base/Switch.tsx
- Switch가 활성화될 때 오른쪽으로 translate animation이 발생하도록 수정했어요.
before
after
- Close #583
=> [#583] Switch 컴포넌트 style 수정

src/v1/base/Input.tsx
- min-width 속성으로 search icon의 최소 영역을 보장하여 해결했어요.
- 수정 전
- 수정 후
- Close #623
=> [#623] [도서 검색] Input 검색 아이콘 Layout Shift 해결

src/app/bookshelf/[bookshelfId]/page.tsx, src/v1/base/BottomNavigation.tsx, src/v1/base/Button.tsx, src/v1/base/Switch.tsx, src/v1/bookGroup/BookInfoCard.tsx, src/v1/bookGroup/SimpleBookGroupCard.tsx, src/v1/bookGroup/create/steps/SelectJoinTypeStep/fields/JoinTypeRadioCard.tsx, src/v1/bookSearch/BestSellers.tsx, src/v1/bookShelf/BookShelf.tsx, tailwind.config.js
- tailwind config에서 사용되지 않는 속성은 제거하고, 하드코딩된 값들을 추가했어요.
- Close #629
=> [#629] tailwind config color 정리

src/components/book/detail/BookInfo.tsx, src/components/comment/CommentList.tsx
- 코멘트 목록, 책 상세페이지 요약글에서 발생하는 text overflow 이슈를 해결했어요
- Close #639
=> [#639] [fix] 코멘트 textoverflow 이슈

src/app/layout.tsx
제 개인 구글 계정의 Search Console에 등록했던 도메인 정보를
새로운 개르발민족 팀 구글 계정으로 이관했어요.
새롭게 옮기면서 google-site-verification이 변경됐습니다
- Close #652
=> [#652] Google SearchConsole을 팀 구글 계정으로 이관

src/app/api/imageOptimize/route.ts, src/components/common/Image.tsx
이미지가 흐리게 보이는 현상이 존재해요
이미지 리사이징 기능을 임시적으로 주석 처리합니다
- Close #673
=> [#673] 이미지 리사이징 기능 임시적으로 주석 처리

src/components/bookGroup/create/steps/SelectBookStep/SelectBookStep.tsx
모임생성 퍼널의 도서선택 스텝에 input 컴포넌트 내부에 x-button를 표시합니다.
- Close #675
=> [#675] [모임 생성] 도서선택 input x-button 추가

src/components/common/Menu.tsx
- Menu.dropdownList 컴포넌트에 dimmed 영역을 추가했어요.
- Close #672
=> [#672] Menu 컴포넌트에 dimmed 영역 추가
